### ISSUE TITLE
feature: Create Habit Screen

### ISSUE THREAD

**Issue by jorgesandia** [S4ND1X/AtomicTracker#27]
Habit screen to save a new one

Firebase will be implemented later on, for now we need to validate and get all inputs from the user, this will be send to Firebase later on

We can leave the save function with a toast saying that data was saved successfully for now

 - **Name**
	 - Text
	 - Required
	 - Validate maximum string size
 - **Frequency**
	 - Spinner
	 - Interval List (e.j every 2 days, every 3 days, ...)
 - **Notifications**
	 - Checkbox or slider
	 - If true Firebase will send notification based on the frequency
 - **Hour  of notification**
	 - Hour
	 - This will be the hour to send a notification and based on the frequency
 - **Start**
	 - Date
	 - Validate selected date, cannot select a date before current day
- **Save**
	- Text or button
	- When saved the habit is saved on Firebase and updated on the habit list

Example of what we want to achieve:

**General idea of the screen**
![image](https://user-images.githubusercontent.com/42609763/144515890-8532d4fa-ce20-4c53-a0fb-2d3f04d9e9bf.png)

**Frequency input**
![image](https://user-images.githubusercontent.com/42609763/144516020-86b3cd61-3b51-46a9-93d1-26cd1aaecf1e.png)
This could help : [Android Spinners](https://developer.android.com/guide/topics/ui/controls/spinner)

**Hour of notification input**
![image](https://user-images.githubusercontent.com/42609763/144516046-ef09832b-828a-41d5-9f76-9798f05f6553.png)
This could help : [Android Pickers](https://developer.android.com/guide/topics/ui/controls/pickers)

**Start input**
![image](https://user-images.githubusercontent.com/42609763/144516071-326b5b6d-cbb8-4eb9-aa5e-b455b2b35be2.png)
This could help : [Android Pickers](https://developer.android.com/guide/topics/ui/controls/pickers)

**Comment by jorgesandia** [comment]
@marleneharms Could you help us with this? :rocket:

**Comment by marleneharms** [comment]
@S4ND1X sure!
